# Generated by Django 5.2.8 on 2026-04-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_about_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mensaje de contacto', 'verbose_name_plural': 'Mensajes de contacto'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Configuración del sitio', 'verbose_name_plural': 'Configuración del sitio'},
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default="Veu d'Eivissa", max_length=100),
        ),
    ]
