# Generated by Django 5.2.8

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contactmessage_options_and_more'),
    ]

    operations = []