# Generated by Django 5.2.8 on 2026-05-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('spotify_url', models.URLField(help_text='Puedes pegar una URL normal o una URL embed de Spotify.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canción de Spotify',
                'verbose_name_plural': 'Canciones de Spotify',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
