# Generated by Django 5.2.8 on 2026-05-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfiguration_spotify_url'),
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120, verbose_name='Nombre del cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email del cliente')),
                ('client_phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono del cliente')),
                ('event_date', models.DateField(verbose_name='Fecha del evento')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Hora aproximada')),
                ('event_location', models.CharField(blank=True, max_length=200, verbose_name='Lugar del evento')),
                ('event_type', models.CharField(blank=True, max_length=120, verbose_name='Tipo de evento')),
                ('guests', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de invitados')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('preferred_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.eventformat', verbose_name='Formato preferido')),
                ('preferred_musician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='musicians.musician', verbose_name='Músico preferido')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
