# Generated by Django 5.2.8 on 2026-06-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventformat',
            name='description_ca',
            field=models.TextField(blank=True, verbose_name='Descripción en catalán'),
        ),
        migrations.AddField(
            model_name='eventformat',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descripción en inglés'),
        ),
        migrations.AddField(
            model_name='eventformat',
            name='title_ca',
            field=models.CharField(blank=True, max_length=120, verbose_name='Título en catalán'),
        ),
        migrations.AddField(
            model_name='eventformat',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Título en inglés'),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='title_ca',
            field=models.CharField(blank=True, max_length=120, verbose_name='Título en catalán'),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Título en inglés'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_text_ca',
            field=models.TextField(blank=True, verbose_name='Texto about en catalán'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_text_en',
            field=models.TextField(blank=True, verbose_name='Texto about en inglés'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_title_ca',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título about en catalán'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_title_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título about en inglés'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_subtitle_ca',
            field=models.TextField(blank=True, verbose_name='Subtítulo hero en catalán'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_subtitle_en',
            field=models.TextField(blank=True, verbose_name='Subtítulo hero en inglés'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_title_ca',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título hero en catalán'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título hero en inglés'),
        ),
    ]
