# Generated by Django 5.2.8 on 2026-04-28 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackofficeUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_musicians', models.BooleanField(default=False, verbose_name='Puede añadir y eliminar músicos')),
                ('can_manage_site_sections', models.BooleanField(default=False, verbose_name='Puede editar secciones de la web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backoffice_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario de backoffice',
                'verbose_name_plural': 'Perfiles de usuarios de backoffice',
            },
        ),
    ]
