# Generated by Django 5.2.8 on 2026-04-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre artístico')),
                ('instrument', models.CharField(max_length=120, verbose_name='Instrumento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción breve')),
                ('image', models.ImageField(blank=True, null=True, upload_to='musicians/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Músico',
                'verbose_name_plural': 'Músicos',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
