# Generated by Django 5.2.8 on 2026-06-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='description_ca',
            field=models.TextField(blank=True, verbose_name='Descripción breve en catalán'),
        ),
        migrations.AddField(
            model_name='musician',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descripción breve en inglés'),
        ),
        migrations.AddField(
            model_name='musician',
            name='instrument_ca',
            field=models.CharField(blank=True, max_length=120, verbose_name='Instrumento en catalán'),
        ),
        migrations.AddField(
            model_name='musician',
            name='instrument_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Instrumento en inglés'),
        ),
    ]
